### ISSUE TITLE
Clicking a region should zoom me into it

### ISSUE THREAD

**Issue by ocdtrekkie** [orblivion/sandstorm-share-a-map#1]
First time I click on the "Boston" pin, it lets me download the Boston map data. But I'm still... nowhere near that zoom level. (In fact, the default zoom level is so far out, the two pins are almost stacked.) Clicking on the Boston pin again... does nothing at all. It feels like it should bring me to that region or zoom level of the map view quickly, instead of needing me to spam the + or double-click endlessly.

**Comment by orblivion** [comment]
Thanks for the feedback. In generally I definitely want to automatically zoom to downloaded areas at convenient times. Maybe right after you download, you zoom to what you just downloaded. Maybe there's a menu on the side with your downloaded areas and you can click one. Maybe on startup it picks a downloaded area to zoom to. Etc. There's definitely _something_ I need to do here. I'm just not sure yet what to do.

I was actually planning at some point to do what you suggested, even if just for demo's sake. However, I'm not sure if I actually want the region pins at all for the first real release. It depends if I'll have the whole world or only have select areas.

I had long considered having a "downloaded areas" menu on the side; you'll want them for updates anyway. If I had that, how would you feel about getting rid of the pins for already-downloaded areas? That would get rid of the stacking problem, and would help you jump from NH to Boston.

**Comment by ocdtrekkie** [comment]
That seems totally reasonable too. (Is it currently reasonable to download NH and Boston into the same grain, now that search is faster?)

**Comment by orblivion** [comment]
Oh yeah for sure.

**Comment by orblivion** [comment]
For now I decided to just have it work when you click the pin, as you suggested.

Latest release should have it. Feel free to reopen if it's not working.
