### ISSUE TITLE
Give caveats for when opening markers in an external app will work

### ISSUE THREAD

**Issue by orblivion** [orblivion/sandstorm-share-a-map#13]
Link text should be "Open in external app (depending on your setup. [Learn More])" Something like that. And then in Learn More give example of what is known to work. (OrganicMaps, OsmAND on Android, Gnome Maps on Linux Desktop) And it may also be browser dependent.

Generally make sure the UX is good, not confusing.

This was discussed in #2

**Comment by orblivion** [comment]
How did this auto-close? Because the message for the above commit says "Fixes #13"? Yikes.

I want to get user feedback before I close this since it's subjective.

**Comment by orblivion** [comment]
@ocdtrekkie Would you mind checking it out and giving an opinion on this? I know it sucks aesthetically (I made a new issue to address that in general) but I'm curious if you think it'd at least make sense to a new user.

**Comment by ocdtrekkie** [comment]
That seems fine to me. I think the expandable explanation is nifty, though I found a UI caveat: If a bookmark is within the top quarter of your screen, and you click it, it repositions the map to fit the entire popup on the screen, which is good. However, then when you click "learn more", the window slides up, off the map, and you have to scroll the map to get up to it. I actually at first though the Learn More caused the rest to disappear entirely, until I realized it had just expanded upwards, and I had tried to click Learn More again to collapse the explanation again.

**Comment by orblivion** [comment]
I didn't see an immediate way to have it pan again to make room for the popup after expanding from Learn More. The initial pan was done by default by Leaflet.js. However there is a way to add padding to the initial pan, so I added 150 pixels to make room for the Learn More expansion. Going with this as a quick fix for now, LMK if the extra panning is obnoxious in regular use.
