### ISSUE TITLE
Onboarding tutorial

### ISSUE THREAD

**Issue by orblivion** [orblivion/sandstorm-share-a-map#18]
This was recommended by a friend who wasn't quite sure what to do when he tried it.

> Maybe have a dialog appear when you first start saying "search for location and bookmark" or have an overlay that points at the search button. Then, point at bookmark after you have the results. 1) search 2) add bookmark Making it numbered makes it more clear that it's a process.

- [x] Warning/explanation about incoming powerbox request
- [x] Let them know about bookmarks
- [x] Let them know they can search for a city on the map right away to help them navigate to the right place they may want to download.
- [x] Make it not too "in your face", let them skip it early on; make it not annoying for repeat users.

**Comment by orblivion** [comment]
Mention that the first thing you have to do is download, and mention that the regions are defined by a file on the map data server, so it's going to ask for download powerbox permissions right away.

Another thought - click "Ok" or a smaller "Skip Tutorial" button. Anybody who's creating a lot of grains will go crazy with the stupid tutorial.

**Comment by orblivion** [comment]
Just released! Interactive for map-downloader user. Simpler for bookmark editors and readonly.

**Comment by timmc** [comment]
It's looking great!
