### ISSUE TITLE
Map regions are extremely faint

### ISSUE THREAD

**Issue by timmc** [orblivion/sandstorm-share-a-map#31]
When the world view first loads, I can barely see the state and country outlines or the downloadable rectangle outlines. For people with low vision it would probably be impossible.

![share-a-map faint](https://github.com/orblivion/sandstorm-share-a-map/assets/78608/2b693308-c385-463a-a309-c4655ea29e79)

**Comment by orblivion** [comment]
The geographic regions part should be considered when doing #3. I could make the existing ones darker for now though.

**Comment by timmc** [comment]
Yeah, the rectangle boundaries might not be very important; as long as the currently-hovered one is visible, that's the important part.

**Comment by orblivion** [comment]
That's what I figured. Did you mean to say that the hover highlight is
faint as well?

**Comment by timmc** [comment]
The hover highlight is pretty faint as well, but wasn't really the part that prompted me to file an issue. I think it's more marginal.

**Comment by orblivion** [comment]
Okay, I did some work on the colors. To the point where I wonder if I really need to worry about #3 for launch anymore.

I made the global background color water-colored, and I made the political base map lighter, with darker borders. At least when you're zoomed out.

![screen-1](https://github.com/orblivion/sandstorm-share-a-map/assets/41976/de3cc5be-92af-4fae-997a-8af08d4acff6)
![screen-2](https://github.com/orblivion/sandstorm-share-a-map/assets/41976/a30cec71-4af4-4e56-8c2b-35389d0eb191)

The current base map I use is geojson. The way leaflet works, it's always overlayed on top of the "tile map" (the one with all the data you download). So, I have to fade out the basemap as you zoom in to your tile map. When I fade out the base map, I don't want the background water color to shine through. So, as soon as I start fading out the base map, I turn the global background to white. When you're by the ocean, you can see.

![screen-3](https://github.com/orblivion/sandstorm-share-a-map/assets/41976/d9d483f2-22a6-4b22-9047-40d107590111)

And then, when you zoom in far enough, the basemap disappears, but hopefully you won't need it by then.

![screen-4](https://github.com/orblivion/sandstorm-share-a-map/assets/41976/da9ea970-b18d-43a3-bf86-35e802c8693d)

@timmc If this looks good to you I'll put it in the next release. (I haven't pushed this change to Github yet).

**Comment by orblivion** [comment]
This is gonna look so much nicer.

**Comment by timmc** [comment]
This looks *great*! :shipit:

**Comment by orblivion** [comment]
Fixed now in the Sandstorm experimental marketplace.
