### ISSUE TITLE
Odd language in deletion box

### ISSUE THREAD

**Issue by timmc** [orblivion/sandstorm-share-a-map#49]
In the deletion dialog, there's an odd bit of language:

> Each area includes the how it looks as well as searchable places.

https://github.com/orblivion/sandstorm-share-a-map/blob/0b80f330a26d53745e8c1430af6203344ca343f7/app.js#L170

I'd submit a PR to fix it but I'm not actually sure what it's trying to say. :-)

**Comment by orblivion** [comment]
I'm trying to convey that each downloadable area includes A) the rendered,
scrollable map ("how it looks") and B) the search index. I want to make
sure the user knows this so they're not confused by not being able to
search for things in that area once they delete it. But I also didn't want
to use technical terms like "render". I'm not surprised this is confusing,
I was sort of rushed.

With that in mind, do you have ideas? Maybe it goes without saying that an
"area" has both of these things, and I could just omit it? I suspect that
when it comes to UI, especially for general audiences, things don't tend to
go without saying. Then again, maybe the default assumption would be not to
even consider that the search index and the render data are different
things. (I'm not sure I would have considered this myself before I started
this project).

Thanks for pointing this out.Message ID:
***@***.***>

>

**Comment by timmc** [comment]
Ah, I see what you're going for there. Yeah, I wouldn't assume that users would consider the different components of an area. I think that in any case it would be more useful to describe the *consequences* of deletion -- that they will no longer be able to see the area or search for places inside it, unless they download it again. But I'd be inclined to leave it unsaid.

**Comment by orblivion** [comment]
Okay I'll just delete that sentence then. Thanks. LMK if you happen on any
other such confusing things, and yeah feel free to PR suggested
rephrasings.Message
ID: ***@***.***>

>

**Comment by orblivion** [comment]
Released with appVersion 29

**Comment by orblivion** [comment]
https://github.com/orblivion/sandstorm-share-a-map/commit/93200c86cb7ec4faad69a09bb29ac74c21aaadd4#diff-e07d531ac040ce3f40e0ce632ac2a059d7cd60f20e61f78268ac3be015b3b28fR174

I changed the language again in case you wanted to check it.
